DROP DATABASE IF EXISTS TEXT_ADVENTURE;
CREATE DATABASE TEXT_ADVENTURE;

USE TEXT_ADVENTURE;

DROP TABLE IF EXISTS MAIN_HISTORY;
CREATE TABLE MAIN_HISTORY(
    ID INT UNSIGNED NOT NULL,
    MAIN_TEXT VARCHAR(1024) NOT NULL,
    FIRST_OPTION VARCHAR(256) NOT NULL,
    SECOND_OPTION VARCHAR(256) NOT NULL,
    FIRST_CHILD INT UNSIGNED NULL,
    SECOND_CHILD INT UNSIGNED NULL,
    IMAGE VARCHAR(256) NULL,
    PRIMARY KEY(ID),
    UNIQUE INDEX UI_FIRST_CHILD(FIRST_CHILD),
    UNIQUE INDEX UI_SECOND_CHILD(SECOND_CHILD)
);

DROP TABLE IF EXISTS RECORDS;
CREATE TABLE RECORDS(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(64) NOT NULL,
    PROGRESS INT UNSIGNED NOT NULL,
    TIME_PLAYED TIME NULL,
    CHARACTER_TYPE VARCHAR(64),
    PRIMARY KEY(ID)
);


/*
ALTER TABLE MAIN_HISTORY ADD FOREIGN KEY(FIRST_CHILD) REFERENCES MAIN_HISTORY(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
						 ADD FOREIGN KEY(SECOND_CHILD) REFERENCES MAIN_HISTORY(ID) ON DELETE RESTRICT ON UPDATE CASCADE;
*/

